GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29kIiwiaWQiOiI2NTk4YjVhZjBjOTQ0ZmUwN2IyMTI3NWQiLCJpYXQiOjE3MDQ1MDY5NTAsImV4cCI6MTcwNDU5MzM1MH0.5-XFAqiu8mvLScDaAhHa8zP7bwgMpz6zeoKsuBpAEuA
Content-Type: application/json

{
    "title": "Test blog 2222222",
    "author": "me",
    "url": "lol",
    "likes": 999999
}

###

DELETE http://localhost:3003/api/blogs/6598952436731709877374e9 HTTP/1.1

###

GET http://localhost:3003/api/blogs/658d663de81308cfd2418407 HTTP/1.1

###

PUT http://localhost:3003/api/blogs/658c8b9ade60d9e841f9fd1c
Content-Type: application/json 

{
    "title": "Updated first Blog",
    "author": "Update bot",
    "url": "update.blog.com/lol",
    "likes": 432
}

###